//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------
using ProtoBuf;
namespace PB
{
	[ProtoContract]
	public class AwardDescInBox
	{
		public AwardDescInBox()
		{
		}

		[ProtoMember(2)]
		public int AwardId;
		[ProtoMember(3)]
		public int AwardNum;
		[ProtoMember(4)]
		public int AwardDurable;
	}
}
