//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------
using ProtoBuf;
namespace PB
{
	[ProtoContract]
	public enum EnumTest
	{

		Role = 1,
		Master = 2,
	}
}
